project_id = "namcnwyhexvtklawagip"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = true

[functions.get-daily-news]
verify_jwt = true