project_id = "namcnwyhexvtklawagip"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = true

[functions.get-daily-news]
verify_jwt = true

[functions.generate-news-image]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.generate-subtitles]
verify_jwt = true

[functions.elevenlabs-session]
verify_jwt = true

[functions.elevenlabs-asr]
verify_jwt = true

[functions.generate-kyrgyz-subtitles]
verify_jwt = true